### PR TITLE
fix(utilities): whitelist case-sensitive tag names (SVG)

### LINKED ISSUE #13: SVG <clipPath> tag is erroneously lowercased
Any SVG `<clipPath>` elements in the parsed document have their tag names lowercased. Unfortunately, SVG is case-sensitive, so this is incorrect.

Smallest reproducible example:
```javascript
const htmlDomParser = require('html-dom-parser')
const dom = htmlDomParser('<svg><clipPath></clipPath></svg>')
dom[0].children[0].name == 'clippath' // true
```

I can try to submit a PR, but I haven't gotten far enough to pin-point the source of the issue yet.

### PR DESCRIPTION
**Pull request by RussianCow**
Fixes #13.

### CODE REVIEW

**Comment by remarkablemark** [comment]
@RussianCow Thanks for taking the time to open the PR.

I took a look at all the possible [SVG tags](https://developer.mozilla.org/en-US/docs/Web/SVG/Element#SVG_elements_A_to_Z) and found even more tags that need to be whitelisted. As a result, I feel that the current approach does not address the root cause and may introduce additional work in the long-term.

Given that [htmlparser2](https://github.com/fb55/htmlparser2/issues/79) is not spec-compliant for SVG's, I'm considering replacing it with [parse5](https://github.com/inikulin/parse5) for server-side parsing.

Does that seem reasonable to you?

**Comment by RussianCow** [comment]
Yep, that's fair—I opened this PR because I ran into this issue in production and wanted to help get a fix out there quickly. :) But I completely agree that my fix is not complete.

That said, a different server-side parsing library wouldn't fix the issue on the client-side though, would it? I'm assuming the `toLowerCase` call is there to support IE, and that's why it can't be removed entirely?

**Comment by remarkablemark** [comment]
Yes, you're correct. The server-side fix can be done in a separate PR.

I think the only reason `.toLowerCase()` was called on the tag name was to be consistent with `htmlparser2`'s output.

In this case, I'm inclined to remove `.toLowerCase()`, but if we do that, we need to mark the feature as a `BREAKING CHANGE` in the commit.

What do you think @RussianCow?

**Comment by RussianCow** [comment]
That sounds good to me! Would you like me to update this PR to make that change instead of the previous one, or do you want to do it yourself?

**Comment by remarkablemark** [comment]
Yes please do @RussianCow.

You can follow this [format](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#commit-message-with-description-and-breaking-change-in-body) for the commit message and do you mind also adding a test? Much appreciated!

**Comment by RussianCow** [comment]
No problem, I'll do that later today.

**Comment by remarkablemark** [comment]
Actually on second thought, let's not cause the breaking change in this PR.

Can you add the additional case-sensitive [tag names](https://developer.mozilla.org/en-US/docs/Web/SVG/Element#SVG_elements_A_to_Z) to the whitelist and add some tests?
- animateMotion
- animateTransform
- clipPath
- feBlend
- feColorMatrix
- feComponentTransfer
- feComposite
- feConvolveMatrix
- feDiffuseLighting
- feDisplacementMap
- feDropShadow
- feFlood
- feFuncA
- feFuncB
- feFuncG
- feFuncR
- feGaussainBlur
- feImage
- feMerge
- feMergeNode
- feMorphology
- feOffset
- fePointLight
- feSpecularLighting
- feSpotLight
- feTile
- feTurbulence
- foreignObject
- linearGradient
- radialGradient
- textPath

**Comment by RussianCow** [comment]
Sure, no problem.

**Comment by RussianCow** [comment]
@remarkablemark Done. Let me know if this works for you.

File: lib/utilities.js [hunk 1]
```diff
@@ -1,5 +1,42 @@
 'use strict';
 
+/**
+ * Constants.
+ */
+var CASE_SENSITIVE_TAGS = [
```
Comment (remarkablemark) [inline lib/utilities.js]: Can we move this to its own file `lib/constants.js`?

Also can we update the JSDoc:
```js
/**
 * SVG elements, unlike HTML elements, are case-sensitive.
 *
 * @see {@link https://developer.mozilla.org/docs/Web/SVG/Element#SVG_elements_A_to_Z}
 */
```

File: lib/utilities.js [hunk 2]
```diff
@@ -131,5 +180,6 @@ function isIE(version) {
 module.exports = {
     formatAttributes: formatAttributes,
     formatDOM: formatDOM,
-    isIE: isIE
+    isIE: isIE,
```
Comment (remarkablemark) [inline lib/utilities.js]: Omit trailing comma as that is not supported in browsers like IE11

Also, once `CASE_SENSITIVE_TAGS` is moved to `lib/constants.js`, we should no longer export it here

File: lib/utilities.js [hunk 3]
```diff
@@ -1,5 +1,42 @@
...
+    'feOffset',
+    'fePointLight',
+    'feSpecularLighting',
+    'feSpotLight',
+    'feTile',
+    'feTurbulence',
+    'foreignObject',
+    'linearGradient',
+    'radialGradient',
+    'textPath',
```
Comment (remarkablemark) [inline lib/utilities.js]: Omit trailing comma as it is only supported in ES6-compliant browsers

File: lib/utilities.js [hunk 4]
```diff
@@ -54,7 +91,19 @@ function formatDOM(nodes, parentObj, directive) {
         // set the node name if it's not "#text" or "#comment"
         // e.g., "div"
         if (node.nodeName.indexOf('#') !== 0) {
-            nodeObj.name = node.nodeName.toLowerCase();
+            var nodeName = null;
+            // SVG elements are case-sensitive, so correct it if it's wrong
+            for (var j = 0; j < CASE_SENSITIVE_TAGS.length; j++) {
```
Comment (remarkablemark) [inline lib/utilities.js]: I don't believe we should correct invalid SVG elements here because I feel it's beyond the scope of what the parser should do and there's a performance cost:
```js
var nodeName = node.nodeName;
// lowercase if element is HTML
if (CASE_SENSITIVE_TAGS.indexOf(nodeName) !== -1) {
  nodeName = nodeName.toLowerCase();
}
nodeObj.name = nodeName;
```

File: test/index.js [hunk 5]
```diff
@@ -44,6 +45,18 @@ function throwTests(parser) {
     });
 }
 
+/**
+ * Tests the case sensitive SVG tags to make sure their case is preserved.
+ *
+ * @param {Function} parser - The parser.
+ */
+function testCaseSensitiveTags(parser) {
```
Comment (remarkablemark) [inline test/index.js]: Thanks for adding the test

File: lib/utilities.js (hunk 3 above)
Comment (RussianCow) [reply lib/utilities.js]: That's actually not true, it's supported in IE >= 9 and is part of ES5. [Source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas)

I can still remove them if you'd like.

File: lib/utilities.js (hunk 4 above)
Comment (RussianCow) [reply lib/utilities.js]: This is what I had originally (although `!==` should be `===`), but it doesn't work because the node name is lowercase already, so it's already incorrect by this point and has to be corrected. That said, I can optimize it to remove the loop.

**Comment by RussianCow** [comment]
@remarkablemark I made a few tweaks, let me know what you think. (Sorry for force-pushing, I know I should just squash at the end but it's habit from my day job.)

File: lib/utilities.js (hunk 3 above)
Comment (remarkablemark) [reply lib/utilities.js]: Ah yes, thanks for the correction. Let's omit them for now until I add a linter to enforce this rule.

File: lib/utilities.js (hunk 4 above)
Comment (remarkablemark) [reply lib/utilities.js]: Yes, I meant `===` instead of `!==`. Thanks for the catch.

**Comment by remarkablemark** [comment]
@RussianCow No worries about the force push, thanks for making the changes.

File: lib/utilities.js [hunk 6]
```diff
@@ -54,7 +59,16 @@ function formatDOM(nodes, parentObj, directive) {
         // set the node name if it's not "#text" or "#comment"
         // e.g., "div"
         if (node.nodeName.indexOf('#') !== 0) {
-            nodeObj.name = node.nodeName.toLowerCase();
+            var nodeName = node.nodeName;
```
Comment (remarkablemark) [inline lib/utilities.js]: Can this be simplified to:
```js
var nodeName = node.nodeName.toLowerCase();
var caseSensitiveTagIndex = CASE_SENSITIVE_TAGS_LOWERCASE.indexOf(nodeName);
// fix case if element is case-sensitive SVG
if (caseSensitiveTagIndex !== -1) {
  nodeName = CASE_SENSITIVe_TAGS[caseSensitiveTagIndex];
}
```

File: lib/constants.js [hunk 7]
```diff
@@ -0,0 +1,44 @@
...
+    'feTile',
+    'feTurbulence',
+    'foreignObject',
+    'linearGradient',
+    'radialGradient',
+    'textPath'
+];
+
+module.exports = {
+    CASE_SENSITIVE_TAGS: CASE_SENSITIVE_TAGS,
```
Comment (remarkablemark) [inline lib/constants.js]: Nit: I missed this one

**Comment by RussianCow** [comment]
@remarkablemark I extracted the case correction code into its own function to simplify it a bit. Let me know if this is good and I'll squash my commits.

**Comment by remarkablemark** [comment]
@RussianCow No worries about squashing the commit. I prefer atomic commits which makes it easier to Git blame.
